/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query AcademyBySlug($slug: String!) {\n  academyBySlug(slug: $slug) {\n    documentId\n    name\n    slug\n    primaryColor\n    secondaryColor\n    plan\n    isActive\n    logo {\n      url\n      alternativeText\n    }\n  }\n}\n\nquery Academies($pagination: PaginationInput) {\n  academies(pagination: $pagination) {\n    documentId\n    name\n    slug\n    plan\n    isActive\n  }\n}": typeof types.AcademyBySlugDocument,
    "query StudentById($documentId: ID!) {\n  student(documentId: $documentId) {\n    documentId\n    name\n    email\n    phone\n    birthdate\n    status\n    notes\n    photo {\n      url\n    }\n    enrollments {\n      documentId\n      status\n      startDate\n      endDate\n      paymentMethod\n      plan {\n        documentId\n        name\n        price\n        billingCycle\n      }\n    }\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n    }\n  }\n}\n\nmutation CreateStudent($data: StudentInput!) {\n  createStudent(data: $data) {\n    documentId\n    name\n    email\n    status\n  }\n}": typeof types.StudentByIdDocument,
    "\n  query AdminDashboard {\n    adminDashboard {\n      metrics {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      recentStudents {\n        id\n        name\n        email\n        plan\n        status\n        initials\n        joinedAt\n      }\n      todayClasses {\n        id\n        name\n        instructor\n        time\n        booked\n        capacity\n      }\n      upcomingPayments {\n        id\n        student\n        amount\n        dueDate\n        method\n      }\n    }\n  }\n": typeof types.AdminDashboardDocument,
    "\n  query FinanceOverview($month: Int, $year: Int) {\n    financeOverview(month: $month, year: $year) {\n      kpis {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      charges {\n        id\n        student\n        studentInitials\n        amount\n        amountFormatted\n        method\n        status\n        dueDate\n        paidAt\n      }\n      methodBreakdown {\n        method\n        label\n        amount\n        percent\n      }\n    }\n  }\n": typeof types.FinanceOverviewDocument,
    "\n  query DREOverview($month: Int, $year: Int) {\n    dreOverview(month: $month, year: $year) {\n      monthLabel\n      revenue {\n        total\n        deltaLabel\n        trend\n      }\n      expenses {\n        total\n        fixed\n        variable\n      }\n      profit {\n        total\n        marginPercent\n      }\n      cashFlow {\n        label\n        revenue\n        expenses\n        profit\n      }\n      categoryBreakdown {\n        category\n        label\n        amount\n        percent\n      }\n      expensesTotalLabel\n      expenseRows {\n        id\n        description\n        subtitle\n        category\n        categoryLabel\n        type\n        dueDate\n        amount\n        status\n      }\n    }\n  }\n": typeof types.DreOverviewDocument,
    "\n  query ScheduleWeek($weekStart: String) {\n    scheduleWeek(weekStart: $weekStart) {\n      weekLabel\n      weekNumber\n      stats {\n        totalClasses\n        totalBookings\n        capacityFill\n      }\n      classes {\n        id\n        name\n        instructor\n        weekday\n        startTime\n        endTime\n        booked\n        capacity\n        color\n      }\n      upcoming {\n        id\n        name\n        time\n        instructor\n      }\n    }\n  }\n": typeof types.ScheduleWeekDocument,
    "\n  query Guardians {\n    guardians {\n      guardian {\n        id\n        name\n        initials\n        email\n        phone\n      }\n      dependents {\n        id\n        name\n        age\n        className\n        classTime\n        status\n        gender\n        medicalAlert\n      }\n    }\n  }\n": typeof types.GuardiansDocument,
    "\n  query AdminWorkouts {\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n      validFrom\n      exercises {\n        name\n        sets\n        reps\n        load\n      }\n      student {\n        documentId\n        name\n      }\n    }\n  }\n": typeof types.AdminWorkoutsDocument,
    "\n  query Students($pagination: PaginationInput) {\n    students(pagination: $pagination) {\n      documentId\n      name\n      email\n      phone\n      status\n      isGuardian\n      enrollments {\n        documentId\n        startDate\n        endDate\n        paymentMethod\n        status\n        plan {\n          documentId\n          name\n          price\n          billingCycle\n        }\n      }\n    }\n  }\n": typeof types.StudentsDocument,
    "\n  query MyAcademy {\n    me {\n      documentId\n      academy {\n        documentId\n        name\n        slug\n        primaryColor\n        secondaryColor\n        plan\n        email\n        phone\n        address\n        logo {\n          url\n          alternativeText\n        }\n      }\n    }\n  }\n": typeof types.MyAcademyDocument,
    "\n  query PricingPlansPublic {\n    plans {\n      documentId\n      name\n      description\n      price\n      billingCycle\n      maxStudents\n      features\n      isActive\n    }\n  }\n": typeof types.PricingPlansPublicDocument,
};
const documents: Documents = {
    "query AcademyBySlug($slug: String!) {\n  academyBySlug(slug: $slug) {\n    documentId\n    name\n    slug\n    primaryColor\n    secondaryColor\n    plan\n    isActive\n    logo {\n      url\n      alternativeText\n    }\n  }\n}\n\nquery Academies($pagination: PaginationInput) {\n  academies(pagination: $pagination) {\n    documentId\n    name\n    slug\n    plan\n    isActive\n  }\n}": types.AcademyBySlugDocument,
    "query StudentById($documentId: ID!) {\n  student(documentId: $documentId) {\n    documentId\n    name\n    email\n    phone\n    birthdate\n    status\n    notes\n    photo {\n      url\n    }\n    enrollments {\n      documentId\n      status\n      startDate\n      endDate\n      paymentMethod\n      plan {\n        documentId\n        name\n        price\n        billingCycle\n      }\n    }\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n    }\n  }\n}\n\nmutation CreateStudent($data: StudentInput!) {\n  createStudent(data: $data) {\n    documentId\n    name\n    email\n    status\n  }\n}": types.StudentByIdDocument,
    "\n  query AdminDashboard {\n    adminDashboard {\n      metrics {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      recentStudents {\n        id\n        name\n        email\n        plan\n        status\n        initials\n        joinedAt\n      }\n      todayClasses {\n        id\n        name\n        instructor\n        time\n        booked\n        capacity\n      }\n      upcomingPayments {\n        id\n        student\n        amount\n        dueDate\n        method\n      }\n    }\n  }\n": types.AdminDashboardDocument,
    "\n  query FinanceOverview($month: Int, $year: Int) {\n    financeOverview(month: $month, year: $year) {\n      kpis {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      charges {\n        id\n        student\n        studentInitials\n        amount\n        amountFormatted\n        method\n        status\n        dueDate\n        paidAt\n      }\n      methodBreakdown {\n        method\n        label\n        amount\n        percent\n      }\n    }\n  }\n": types.FinanceOverviewDocument,
    "\n  query DREOverview($month: Int, $year: Int) {\n    dreOverview(month: $month, year: $year) {\n      monthLabel\n      revenue {\n        total\n        deltaLabel\n        trend\n      }\n      expenses {\n        total\n        fixed\n        variable\n      }\n      profit {\n        total\n        marginPercent\n      }\n      cashFlow {\n        label\n        revenue\n        expenses\n        profit\n      }\n      categoryBreakdown {\n        category\n        label\n        amount\n        percent\n      }\n      expensesTotalLabel\n      expenseRows {\n        id\n        description\n        subtitle\n        category\n        categoryLabel\n        type\n        dueDate\n        amount\n        status\n      }\n    }\n  }\n": types.DreOverviewDocument,
    "\n  query ScheduleWeek($weekStart: String) {\n    scheduleWeek(weekStart: $weekStart) {\n      weekLabel\n      weekNumber\n      stats {\n        totalClasses\n        totalBookings\n        capacityFill\n      }\n      classes {\n        id\n        name\n        instructor\n        weekday\n        startTime\n        endTime\n        booked\n        capacity\n        color\n      }\n      upcoming {\n        id\n        name\n        time\n        instructor\n      }\n    }\n  }\n": types.ScheduleWeekDocument,
    "\n  query Guardians {\n    guardians {\n      guardian {\n        id\n        name\n        initials\n        email\n        phone\n      }\n      dependents {\n        id\n        name\n        age\n        className\n        classTime\n        status\n        gender\n        medicalAlert\n      }\n    }\n  }\n": types.GuardiansDocument,
    "\n  query AdminWorkouts {\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n      validFrom\n      exercises {\n        name\n        sets\n        reps\n        load\n      }\n      student {\n        documentId\n        name\n      }\n    }\n  }\n": types.AdminWorkoutsDocument,
    "\n  query Students($pagination: PaginationInput) {\n    students(pagination: $pagination) {\n      documentId\n      name\n      email\n      phone\n      status\n      isGuardian\n      enrollments {\n        documentId\n        startDate\n        endDate\n        paymentMethod\n        status\n        plan {\n          documentId\n          name\n          price\n          billingCycle\n        }\n      }\n    }\n  }\n": types.StudentsDocument,
    "\n  query MyAcademy {\n    me {\n      documentId\n      academy {\n        documentId\n        name\n        slug\n        primaryColor\n        secondaryColor\n        plan\n        email\n        phone\n        address\n        logo {\n          url\n          alternativeText\n        }\n      }\n    }\n  }\n": types.MyAcademyDocument,
    "\n  query PricingPlansPublic {\n    plans {\n      documentId\n      name\n      description\n      price\n      billingCycle\n      maxStudents\n      features\n      isActive\n    }\n  }\n": types.PricingPlansPublicDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query AcademyBySlug($slug: String!) {\n  academyBySlug(slug: $slug) {\n    documentId\n    name\n    slug\n    primaryColor\n    secondaryColor\n    plan\n    isActive\n    logo {\n      url\n      alternativeText\n    }\n  }\n}\n\nquery Academies($pagination: PaginationInput) {\n  academies(pagination: $pagination) {\n    documentId\n    name\n    slug\n    plan\n    isActive\n  }\n}"): (typeof documents)["query AcademyBySlug($slug: String!) {\n  academyBySlug(slug: $slug) {\n    documentId\n    name\n    slug\n    primaryColor\n    secondaryColor\n    plan\n    isActive\n    logo {\n      url\n      alternativeText\n    }\n  }\n}\n\nquery Academies($pagination: PaginationInput) {\n  academies(pagination: $pagination) {\n    documentId\n    name\n    slug\n    plan\n    isActive\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query StudentById($documentId: ID!) {\n  student(documentId: $documentId) {\n    documentId\n    name\n    email\n    phone\n    birthdate\n    status\n    notes\n    photo {\n      url\n    }\n    enrollments {\n      documentId\n      status\n      startDate\n      endDate\n      paymentMethod\n      plan {\n        documentId\n        name\n        price\n        billingCycle\n      }\n    }\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n    }\n  }\n}\n\nmutation CreateStudent($data: StudentInput!) {\n  createStudent(data: $data) {\n    documentId\n    name\n    email\n    status\n  }\n}"): (typeof documents)["query StudentById($documentId: ID!) {\n  student(documentId: $documentId) {\n    documentId\n    name\n    email\n    phone\n    birthdate\n    status\n    notes\n    photo {\n      url\n    }\n    enrollments {\n      documentId\n      status\n      startDate\n      endDate\n      paymentMethod\n      plan {\n        documentId\n        name\n        price\n        billingCycle\n      }\n    }\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n    }\n  }\n}\n\nmutation CreateStudent($data: StudentInput!) {\n  createStudent(data: $data) {\n    documentId\n    name\n    email\n    status\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AdminDashboard {\n    adminDashboard {\n      metrics {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      recentStudents {\n        id\n        name\n        email\n        plan\n        status\n        initials\n        joinedAt\n      }\n      todayClasses {\n        id\n        name\n        instructor\n        time\n        booked\n        capacity\n      }\n      upcomingPayments {\n        id\n        student\n        amount\n        dueDate\n        method\n      }\n    }\n  }\n"): (typeof documents)["\n  query AdminDashboard {\n    adminDashboard {\n      metrics {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      recentStudents {\n        id\n        name\n        email\n        plan\n        status\n        initials\n        joinedAt\n      }\n      todayClasses {\n        id\n        name\n        instructor\n        time\n        booked\n        capacity\n      }\n      upcomingPayments {\n        id\n        student\n        amount\n        dueDate\n        method\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FinanceOverview($month: Int, $year: Int) {\n    financeOverview(month: $month, year: $year) {\n      kpis {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      charges {\n        id\n        student\n        studentInitials\n        amount\n        amountFormatted\n        method\n        status\n        dueDate\n        paidAt\n      }\n      methodBreakdown {\n        method\n        label\n        amount\n        percent\n      }\n    }\n  }\n"): (typeof documents)["\n  query FinanceOverview($month: Int, $year: Int) {\n    financeOverview(month: $month, year: $year) {\n      kpis {\n        id\n        label\n        value\n        highlighted\n        delta {\n          value\n          trend\n        }\n      }\n      charges {\n        id\n        student\n        studentInitials\n        amount\n        amountFormatted\n        method\n        status\n        dueDate\n        paidAt\n      }\n      methodBreakdown {\n        method\n        label\n        amount\n        percent\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DREOverview($month: Int, $year: Int) {\n    dreOverview(month: $month, year: $year) {\n      monthLabel\n      revenue {\n        total\n        deltaLabel\n        trend\n      }\n      expenses {\n        total\n        fixed\n        variable\n      }\n      profit {\n        total\n        marginPercent\n      }\n      cashFlow {\n        label\n        revenue\n        expenses\n        profit\n      }\n      categoryBreakdown {\n        category\n        label\n        amount\n        percent\n      }\n      expensesTotalLabel\n      expenseRows {\n        id\n        description\n        subtitle\n        category\n        categoryLabel\n        type\n        dueDate\n        amount\n        status\n      }\n    }\n  }\n"): (typeof documents)["\n  query DREOverview($month: Int, $year: Int) {\n    dreOverview(month: $month, year: $year) {\n      monthLabel\n      revenue {\n        total\n        deltaLabel\n        trend\n      }\n      expenses {\n        total\n        fixed\n        variable\n      }\n      profit {\n        total\n        marginPercent\n      }\n      cashFlow {\n        label\n        revenue\n        expenses\n        profit\n      }\n      categoryBreakdown {\n        category\n        label\n        amount\n        percent\n      }\n      expensesTotalLabel\n      expenseRows {\n        id\n        description\n        subtitle\n        category\n        categoryLabel\n        type\n        dueDate\n        amount\n        status\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ScheduleWeek($weekStart: String) {\n    scheduleWeek(weekStart: $weekStart) {\n      weekLabel\n      weekNumber\n      stats {\n        totalClasses\n        totalBookings\n        capacityFill\n      }\n      classes {\n        id\n        name\n        instructor\n        weekday\n        startTime\n        endTime\n        booked\n        capacity\n        color\n      }\n      upcoming {\n        id\n        name\n        time\n        instructor\n      }\n    }\n  }\n"): (typeof documents)["\n  query ScheduleWeek($weekStart: String) {\n    scheduleWeek(weekStart: $weekStart) {\n      weekLabel\n      weekNumber\n      stats {\n        totalClasses\n        totalBookings\n        capacityFill\n      }\n      classes {\n        id\n        name\n        instructor\n        weekday\n        startTime\n        endTime\n        booked\n        capacity\n        color\n      }\n      upcoming {\n        id\n        name\n        time\n        instructor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Guardians {\n    guardians {\n      guardian {\n        id\n        name\n        initials\n        email\n        phone\n      }\n      dependents {\n        id\n        name\n        age\n        className\n        classTime\n        status\n        gender\n        medicalAlert\n      }\n    }\n  }\n"): (typeof documents)["\n  query Guardians {\n    guardians {\n      guardian {\n        id\n        name\n        initials\n        email\n        phone\n      }\n      dependents {\n        id\n        name\n        age\n        className\n        classTime\n        status\n        gender\n        medicalAlert\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AdminWorkouts {\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n      validFrom\n      exercises {\n        name\n        sets\n        reps\n        load\n      }\n      student {\n        documentId\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query AdminWorkouts {\n    workoutPlans {\n      documentId\n      name\n      instructor\n      isActive\n      validFrom\n      exercises {\n        name\n        sets\n        reps\n        load\n      }\n      student {\n        documentId\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Students($pagination: PaginationInput) {\n    students(pagination: $pagination) {\n      documentId\n      name\n      email\n      phone\n      status\n      isGuardian\n      enrollments {\n        documentId\n        startDate\n        endDate\n        paymentMethod\n        status\n        plan {\n          documentId\n          name\n          price\n          billingCycle\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Students($pagination: PaginationInput) {\n    students(pagination: $pagination) {\n      documentId\n      name\n      email\n      phone\n      status\n      isGuardian\n      enrollments {\n        documentId\n        startDate\n        endDate\n        paymentMethod\n        status\n        plan {\n          documentId\n          name\n          price\n          billingCycle\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MyAcademy {\n    me {\n      documentId\n      academy {\n        documentId\n        name\n        slug\n        primaryColor\n        secondaryColor\n        plan\n        email\n        phone\n        address\n        logo {\n          url\n          alternativeText\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query MyAcademy {\n    me {\n      documentId\n      academy {\n        documentId\n        name\n        slug\n        primaryColor\n        secondaryColor\n        plan\n        email\n        phone\n        address\n        logo {\n          url\n          alternativeText\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PricingPlansPublic {\n    plans {\n      documentId\n      name\n      description\n      price\n      billingCycle\n      maxStudents\n      features\n      isActive\n    }\n  }\n"): (typeof documents)["\n  query PricingPlansPublic {\n    plans {\n      documentId\n      name\n      description\n      price\n      billingCycle\n      maxStudents\n      features\n      isActive\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;